### ISSUE TITLE
Sumo reports an error "Error: Answered with error to command 0xa3: Lane '' is not known" after running test.py

### ISSUE THREAD

**Issue by paperh0rse** [federicovergallo/SUMO-changing-lane-agent#4]
![image](https://user-images.githubusercontent.com/61502023/121659930-5baf6c00-cad5-11eb-8910-a90c032990b8.png)

**Comment by CLQ0425** [comment]
Same error.How did you solve it？

**Comment by federicovergallo** [comment]
Hi all,

This is more a warning than an error actually and it does not prevent you from training/testing the agent. Basically SUMO, in presence of collision, put the agent in a sort of "teleported list" because phisically move the agent from a side to another of the network. The agent, at the time of the collision, is not aware of being put in this list and still tries to do some action, but of course the name of the lanes are empty because he's in the teleportation list.

I handle this "error" by doing a simulation step meanwhile the agent is back on the network. Still, it's not a real error and you should not really care of it (this said, you can try some smarter way to deal with it :D )

hope it's clear and I'm really sorry of not having replied before, but this is an old university project and I don't take care of it anymore.
